<?php require 'templates/layout/header.phtml';
    require 'templates/form_alta_registro.phtml';
?>


<div class="container mt-4">
    <h2>Registros</h2>
    <form action="buscar" method="GET" class="mb-4">
    <div class="row">
        <div class="col">
            <select name="establecimiento" class="form-control" id="establecimiento">
                <option value="" disabled selected>Selecciona un establecimiento</option>
                <?php foreach ($establecimientos as $establecimiento): ?>
                    <option value="<?= htmlspecialchars($establecimiento->id) ?>">
                        <?= htmlspecialchars($establecimiento->nombre) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </div>
</form>

    
    <ul class="list-group">
        <?php foreach($registros as $registro): ?>
            <li class="list-group-item item-registro <?php if($registro->finalizada): ?> finished <?php endif ?>">
                <div class="label">
                    <b>| Nombre: <?= htmlspecialchars($registro->nombre) ?></b> |
                    Accion: <?= substr($registro->action, 0, 25) ?> |
                    (Fecha: <?= $registro->fecha ?>)
                </div>
                <div class="actions">
                        <a href="modificar/<?= $registro->id ?>" type="button" class="btn btn-primary btn-sm me-2">Modificar</a>
                    <a href="eliminar/<?= $registro->id ?>" type="button" class="btn btn-danger btn-sm">Borrar</a>
                </div>
            </li>
        <?php endforeach ?>
    </ul>

    <p class="mt-3"><small>Mostrando <?= $count ?> registros</small></p>
</div>

<?php require 'templates/layout/footer.phtml' ?>
