<?php require 'templates/header.tpl';
    require 'templates/form_alta_registro.tpl';
?>


<div class="container mt-4">
    <h2>Registros</h2>
    
    <ul class="list-group">
        <?php foreach($registros as $registro): ?>
            <li class="list-group-item item-registro <?php if($registro->finalizada): ?> finished <?php endif ?>">
                <div class="label">
                    <b>| Nombre: <?= htmlspecialchars($registro->nombre) ?></b> |
                    Accion: <?= substr($registro->action, 0, 25) ?> |
                    (Fecha: <?= $registro->fecha ?>)
                </div>
                <div class="actions">
                        <a href="modificar/<?= $registro->id ?>" type="button" class="btn btn-primary btn-sm me-2">Modificar</a>
                    <a href="eliminar/<?= $registro->id ?>" type="button" class="btn btn-danger btn-sm">Borrar</a>
                </div>
            </li>
        <?php endforeach ?>
    </ul>

    <p class="mt-3"><small>Mostrando <?= $count ?> registros</small></p>
</div>

<?php require 'templates/footer.tpl' ?>
